# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'EWA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EWA
pod 'SwiftyJSON'
pod 'FSCalendar'
pod 'SideMenuController'
pod 'ExpyTableView'
pod 'IQKeyboardManagerSwift'
pod 'ANLoader'
pod 'DropDown'
pod 'Toast-Swift', '~> 3.0.1'
pod 'SDWebImage', '~> 4.0'
#pod 'Fabric'
#pod 'Crashlytics', '~>  3.10'
pod 'ActiveLabel'
pod 'CropViewController'
pod 'KMPlaceholderTextView', '~> 1.3.0'
pod 'FacebookCore'
pod 'FacebookLogin'
pod 'FacebookShare'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'Firebase/Crashlytics'
pod 'Firebase/Messaging'
pod 'PDFReader'
pod 'MXSegmentedPager'
pod 'MXSegmentedControl'
pod 'JVFloatLabeledTextField'
#pod 'APScheduledLocationManager' // removed pod and added file 
pod 'SkyFloatingLabelTextField', '~> 3.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "13.0"
    end
  end
end
