# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'CWA' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CWA

  target 'CWATests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CWAUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'SwiftyJSON'
pod 'SDWebImage'
pod 'FSCalendar'
pod 'Toast-Swift'
pod 'DropDown'
pod 'IQKeyboardManagerSwift'
pod 'Firebase/Crashlytics'
pod 'FloatRatingView'
pod 'GoogleMaps', '~> 8.4'    # or latest available
pod 'GooglePlaces', '~> 8.4'
pod 'Firebase/Core'
pod 'Firebase/Analytics'
pod 'KMPlaceholderTextView'
pod "RecaptchaEnterprise" 
#, "18.3.0"
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }

	config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = "14.0"

    end
  end

end

